// src/components/Footer.svelte
<footer>
	<hr />
	<p id="copyright">
		Website developed by Harrison Bouche. © {new Date().getFullYear()}
	</p>
</footer>

<style>
footer {
	padding-top: 1rem;

	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;
}

hr {
	width: 90%;
	max-width: 575px;
	height: 0px;

	border: 0;
	border-top: 5px dotted;
}

p {
	margin: 1rem;

	color: var(--clr-tan-primary);

	font-weight: bold;
}
</style>

// src/components/Footer.tsx
import React from "react"
import Spacer from "./Spacer"

export default () => (
	<footer className="flex flex-col items-center justify-center">
		<Spacer />
		<hr className="h-0 w-4/5 max-w-xl border-0 border-t-4 border-dotted border-primary" />
		<p className="m-5 font-bold text-primary">
			Website developed by Harrison Bouche. © 2024
		</p>
	</footer>
)
