// src/components/Gallery.svelte
<script lang="ts">
	import { onMount } from "svelte"

	export let galleryJson: string
	export let galleryName: string

	type picture = {
		source: string
		alt: string
		caption: string
	}

	// Get supplied picture array
	let picturesArr: Array<picture> = []

	onMount(() => {
		fetch(`${galleryJson}/gallery.json`)
			.then((response) => {
				if (response.ok) {
					return response.json()
				} else {
					throw new Error("status " + response.status)
				}
			})
			.then((json) => {
				picturesArr = [...json[galleryName]]
			})
	})

	// TODO: create lightbox to view images
	// const galleryArr = [...document.getElementsByClassName("picture")];
	// for(const picture of galleryArr) {
	//     picture.addEventListener("click", () => {
	//         console.log(galleryArr.indexOf(picture)); // use this to switch between images, eventually
	//     })
	// };
</script>

<div>
	<div class="pictures-box">
		{#each picturesArr as image}
			<div
				class="picture {picturesArr.length == 1
					? 'pictures-length1'
					: picturesArr.length == 2
					? 'pictures-length2'
					: picturesArr.length == 3
					? 'pictures-length3'
					: 'pictures-length4plus'}"
				style={`background-image: url(${image.source})`}
				title={image.alt}
			/>
		{/each}
	</div>
	{#if picturesArr.length == 1}
		<p class="txt-sml txt-wi txt-alc" style="margin-bottom: 1rem">
			{picturesArr[0].caption}
		</p>
	{/if}
</div>

<style>
	.pictures-box {
		aspect-ratio: 16 / 9;
		margin: 18px 0;

		display: grid;
		grid-template-columns: repeat(6, 1fr);
		grid-template-rows: repeat(6, 1fr);
		gap: 12px;
	}

	.picture {
		background-size: cover;
		background-position: center;
		border-radius: 12px;
		box-shadow: 0 3px 9px var(--clr-tan-tertiary);
		cursor: pointer;

		transition: 0.5s cubic-bezier(0.075, 0.82, 0.165, 1);
	}

	.picture:hover {
		transform: translateY(-3px);
		box-shadow: 0 9px 15px var(--clr-tan-tertiary);
	}

	.pictures-length1 {
		grid-area: 1 / 1 / 7 / 7;
	}

	.pictures-length2:nth-of-type(1) {
		grid-area: 1 / 1 / 7 / 4;
	}
	.pictures-length2:nth-of-type(2) {
		grid-area: 1 / 4 / 7 / 7;
	}

	.pictures-length3:nth-of-type(1) {
		grid-area: 1 / 1 / 7 / 5;
	}
	.pictures-length3:nth-of-type(2) {
		grid-area: 1 / 5 / 4 / 7;
	}
	.pictures-length3:nth-of-type(3) {
		grid-area: 4 / 5 / 7 / 7;
	}

	.pictures-length4plus:nth-of-type(1) {
		grid-area: 1 / 1 / 7 / 5;
	}
	.pictures-length4plus:nth-of-type(2) {
		grid-area: 1 / 5 / 3 / 7;
	}
	.pictures-length4plus:nth-of-type(3) {
		grid-area: 3 / 5 / 5 / 7;
	}
	.pictures-length4plus:nth-of-type(4) {
		grid-area: 5 / 5 / 7 / 7;
	}
</style>

// src/components/Gallery/Gallery.tsx
import clsx from 'clsx';
import { useEffect, useState } from 'react';
import styles from './Gallery.module.css';

interface picture {
    source: string;
    alt: string;
    caption: string;
}

export default function Gallery(props: { galleryJson: string, galleryName: string }) {

    // Get supplied picture array
    const [picturesArr, setPicturesArr] = useState<picture[]>([]);
    useEffect(() => {
        fetch(`${props.galleryJson}/gallery.json`)
            .then((response) => {
                if(response.ok) {
                    return response.json();
                } else {
                    throw new Error("status" + response.status);
                }
            })
            .then((json) => {
                setPicturesArr([...json[props.galleryName]]);
            })
    }, []);

    // TODO: create lightbox to view images
    // const galleryArr = [...document.getElementsByClassName("picture")];
    // for(const picture of galleryArr) {
    //     picture.addEventListener("click", () => {
    //         console.log(galleryArr.indexOf(picture)); // use this to switch between images, eventually
    //     })
    // };

    return (
        <div>
            <div id={styles["pictures-box"]}>
                {picturesArr.map(image => (
                    <div
                        className={
                            clsx(
                                styles["picture"],
                                picturesArr.length == 1 ?
                                    styles["pictures-length1"] : picturesArr.length == 2 ?
                                        styles["pictures-length2"] : picturesArr.length == 3 ?
                                            styles["pictures-length3"] : styles["pictures-length4plus"])}
                        style={{backgroundImage: `url(${image.source})`}}
                        title={image.alt}
                        key={image.alt}
                    />
                ))}
            </div>
            {picturesArr.length == 1 ? <p className="txt-sml txt-wi txt-alc" style={{marginBottom: "1rem"}} >{picturesArr[0].caption}</p> : <></>}
        </div>
    );
}
